apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: postgres-targetgroup-binding
  namespace: "{{ $sys.id }}"
spec:
  serviceRef:
    namespace: "{{ $sys.id }}"
    name: helm-postgresql # This is the name of the service that the target group will be bound to
    port: 5432
  targetGroupARN: "{{ $terraform.out.target_group_arn }}"